#!/usr/bin/env zsh
# A script for installing dependencies and setting up needed Symbolic Links
# Created by Jeremy Dwayne
# Modified by Blake Ridgway
# Updated 02/13/2021
# NOTICE: Modify script to your own preferences! This mostly uses default
#         locations, but can be changed to whatever you need.

git submodule init
git submodule update --recursive

# Installs tilix
sudo apt install tilix

# Oh My ZSH is installer
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Grab and configure powerlevel9k
# git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k

# POWERLEVEL10K
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# Copy p10k Config file
cp .p10k.zsh ~/

# Grabs Nerd Font and configures it
wget https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf
mkdir -p ~/.local/share/fonts 
cp Hack\ Regular\ Nerd\ Font\ Complete.ttf ~/.local/share/fonts/
fc-cache -f -v

# Install Rust
 echo 'install rust'
 curl https://sh.rustup.rs -sSf | sh

# Fancy ls script taken from github.com/brandonroehl/dotfiles
files=( 'vimrc' 'vim' 'zshrc' 'zsh' 'agignore' 'gitconfig' 'gitignore' 'gitmessage' 'gemrc' 'rspec' 'eslintrc' )
for file in $files
do
  echo ""
  echo "Simlinking $file to $HOME"
  ln -sf "$PWD/$file" "$HOME/.$file"
  if [ $? -eq 0 ]
  then
    echo "$PWD/$file ~> $HOME/.$file"
  else
    echo 'Install failed to symlink.'
    exit 1
  fi
done
