#!/usr/bin/env zsh
# A script for installing dependencies and setting up needed Symbolic Links
# Created by Blake Ridgway
# Updated 07/01/2020
# NOTICE: Modify script to your own preferences! This mostly uses default
#         locations, but can be changed to whatever you need.

git submodule init
git submodule update --recursive

# Installs tilix
sudo apt install tilix

# Check to see if Oh My ZSH is installed
if ! [ -d "$HOME/.oh-my-zsh/" ]; then
  echo >&2 "oh-my-zsh is not installed, fixing that...";
  curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
fi

# Grab and configure powerlevel9k
git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k

# Grabs Nerd Font and configures it
wget https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf
mkdir -p ~/.local/share/fonts 
cp Hack\ Regular\ Nerd\ Font\ Complete.ttf ~/.local/share/fonts/
fc-cache -f -v

# Check to see if Rust is installed.
# echo 'install rust'
# curl https://sh.rustup.rs -sSf | sh

# Fancy ls script taken from github.com/brandonroehl/dotfiles
files=( 'vimrc' 'vim' 'zshrc' 'zsh' 'agignore' 'gitconfig' 'gitignore' 'gitmessage' 'gemrc' 'rspec' 'eslintrc' )
for file in $files
do
  echo ""
  echo "Simlinking $file to $HOME"
  ln -sf "$PWD/$file" "$HOME/.$file"
  if [ $? -eq 0 ]
  then
    echo "$PWD/$file ~> $HOME/.$file"
  else
    echo 'Install failed to symlink.'
    exit 1
  fi
done
