#!/bin/bash

# Installs rbenv

rbenv install 2.7.2
rbenv global 2.7.2
ruby -v

# Insalls Bundler

gem install bundler
rbenv rehash

# Installs Rails Version 6.

gem install rails -v 6.0.3.4
rbenv rehash
