#!/bin/bash

# Installs rbenv

rbenv install 3.0.1
rbenv global 3.0.1
ruby -v

# Insalls Bundler

gem install bundler
rbenv rehash

# Installs Rails Version 6.

gem install rails -v 6.1.3.2
rbenv rehash
